.TH "Music Player Command" 1
.SH "NAME"
mpc \- Program for controlling Music Player Daemon (MPD)
.SH "SYNOPSIS"
mpc [<command> <arguments>]
.SH "DESCRIPTION"
mpc is a client for MPD, the Music Player Daemon. mpc connects to a MPD running on a machine on the local network and controls MPD according to commands and arguments passed to it. If no arguments are passed, current status is given. 

.SH "OPTIONS"
.TP
.BI --format
.br
Configure the format of song display for status and the playlist.  The metadata delimeters are "%name%", "%artist%", "%album%", "%title%", "%track%", "%time%", and "%file%".  The [] operator is used to group output such that if no metadata delimeters are found or matched between '[' and ']', then none of the characters between '[' and ']' are output.  '&' and '|' are logical operators for and and or.  '#' is used to escape characters.  Some useful examples for format are: "%file%" and "[[%artist% - ]%title%]|[%file%]"
.SH COMMANDS 
.TP
.B add <song>
Adds a song from the music database to the playlist. Can also read input from pipes. Use "mpc ls | mpc add" to add all files to the playlist.
.TP
.B clear
Empties playlist.
.TP
.B crop
Remove all songs except for the currently playing song.
.TP
.B crossfade [<seconds>]
Gets and sets the current amount of crossfading between songs (0 disables crossfading).
.TP
.B del <song>
Removes a song from the playlist. Can also read input from pipes.
.TP
.B listall [<song>]
Lists <song> from playlist. If no <song> is specified, lists all songs.
.TP
.B load <file>
Loads <file> as playlist.
.TP
.B ls [<directory>]
Lists all files/folders in <directory>. If no <directory> is specified, lists all files in music directory.
.TP
.B lsplaylists
Lists available playlists.
.TP 
.B move <from> <to>
Moves song at position <from> to the postion <to> in the playlist.
.TP
.B next
Starts playing next song on playlist.
.TP
.B pause
Pauses playing.
.TP
.B play <number>
Starts playing the song-number specified. If none is specified, plays number 1.
.TP
.B playlist
Prints entire playlist.
.TP
.B prev
Starts playing previous song.
.TP
.B random [<state>]
Toggle random mode if state ("on" or "off") is not specified.
.TP
.B repeat [<state>]
Toggle repeat mode if state ("on" or "off") is not specified.
.TP
.B rm <file>
Deletes a specific playlist.
.TP
.B save <file>
Saves playlist as <file>.
.TP
.B search <table> <pattern>
Searches for songs that match the pattern, where table is "artist", "album", "title", or "filename".
.TP
.B seek [+-][<HH:MM:SS>] or <[+-]<0-100>%>
Seeks by hour, minute or seconds, hours or minutes can be omitted.
If seeking by percentage, seeks within the current song in the specified manner.  If a "+" or "-" is used, the seek is done relative to the current song position. Absolute seeking by default.
.TP
.B shuffle
Shuffles all songs on the playlist.
.TP
.B stats
Displays statistics about MPD
.TP
.B stop
Stops playing.
.TP
.B toggle
Toggles between play and pause. If stopped starts playing. Does not support start playing at song number (use play).
.TP
.B update [<path>]
Scans music directory for updates if no <path> is specified.  If one or more <path>'s are specified, scans only those path's for updates.  Can take input from a pipe.
.TP
.B version
Reports the version of MPD.
.TP
.B volume <[+-]value>
Sets the volume to <value> (0-100).  If "+" or "-" is used, then it adjusts
the volume relative to the current volume.
.SH "ENVIRONMENT"
.TP
This section describes some environment variables that affect how mpc operates.
.br
	MPD_HOST
.br
	MPD_PORT
.br
		By default, mpc connects to localhost:6600. This can be changed either at compile-time, or by exporting the MPD_HOST and MPD_PORT environment variables.
.br
		To use a password with mpd, set MPD_HOST to password@host.
.SH "EXAMPLES"
.TP
Here is a script to load and play m3u playlists (useful for mozilla):
.br

.br
#!/bin/bash
.br
mpc clear
.br
cat $1 | mpc add
.br
mpc play
.br
.TP
This script can be used to load and play pls playlists (again, useful for mozilla):
.br

.br
#!/bin/bash
.br
mpc clear
.br
grep '^File[0-9]*' $1 | sed -e 's/^File[0-9]*=//' | mpc add
.br
mpc play
.br
.SH "BUGS"
Report bugs on http://www.musicpd.org/mantis/
.SH "NOTE"
Since MPD uses UTF\-8, mpc needs to convert characters to the
charset used by the local system. If you get character conversion errors when your running mpc you probably need to set up your locale. This is done by setting any of the LC_CTYPE, LANG or LC_ALL enviroment vatiables (LC_CTYPE only affects character handling).
.SH "SEE ALSO"
mpd(1)
.SH "AUTHOR"
	See <http://svn.musicpd.org/mpc/trunk/AUTHORS>, for contributors to mpc
